# Categorical Feature Encoding

## Objective
The objective of this notebook is to convert categorical variables into numerical representations suitable for machine learning models. The encoded dataset will be used for model training and evaluation.

In [92]:
# Import Libraries

import pandas as pd

In [93]:
# Load feature engineered dataset

df=pd.read_csv("../data/processed/feature_engineered_telco_churn.csv")
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,TotalServices,TenureGroup,MonthlyChargeCategory,LongTermCustomer
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,...,Month-to-month,Yes,Electronic check,29.85,29.85,No,2,0-12,Low,0
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,...,One year,No,Mailed check,56.95,1889.50,No,5,25-48,Medium,1
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,4,0-12,Medium,0
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,...,One year,No,Bank transfer (automatic),42.30,1840.75,No,5,25-48,Medium,1
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,2,0-12,High,0

In [94]:
# Dataset information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   gender                 7032 non-null   object
 1   SeniorCitizen          7032 non-null   int64
 2   Partner                7032 non-null   object
 3   Dependents             7032 non-null   object
 4   tenure                 7032 non-null   int64
 5   PhoneService           7032 non-null   object
 6   MultipleLines          7032 non-null   object
 7   InternetService        7032 non-null   object
 8   OnlineSecurity         7032 non-null   object
 9   OnlineBackup           7032 non-null   object
 10  DeviceProtection       7032 non-null   object
 11  TechSupport            7032 non-null   object
 12  StreamingTV            7032 non-null   object
 13  StreamingMovies        7032 non-null   object
 14  Contract               7032 non-null   object
 15  PaperlessBilling       7032 non-null   object
 16  PaymentMethod          7032 non-null   object
 17  MonthlyCharges         7032 non-null   float64
 18  TotalCharges           7032 non-null   float64
 19  Churn                  7032 non-null   object
 20  TotalServices          7032 non-null   int64
 21  TenureGroup            7032 non-null   object
 22  MonthlyChargeCategory  7032 non-null   object
 23  LongTermCustomer       7032 non-null   int64
dtypes: float64(2), int64(4), object(18)
memory usage: 1.3+ MB

In [95]:
# Inspect categorical values before encoding
for col in df.select_dtypes(include="object").columns:
    print(col)
    print(df[col].unique())
    print("-" * 30)

gender
['Female' 'Male']
------------------------------
Partner
['Yes' 'No']
------------------------------
Dependents
['No' 'Yes']
------------------------------
PhoneService
['No' 'Yes']
------------------------------
MultipleLines
['No phone service' 'No' 'Yes']
------------------------------
InternetService
['DSL' 'Fiber optic' 'No']
------------------------------
OnlineSecurity
['No' 'Yes' 'No internet service']
------------------------------
OnlineBackup
['Yes' 'No' 'No internet service']
------------------------------
DeviceProtection
['No' 'Yes' 'No internet service']
------------------------------
TechSupport
['No' 'Yes' 'No internet service']
------------------------------
StreamingTV
['No' 'Yes' 'No internet service']
------------------------------
StreamingMovies
['No' 'Yes' 'No internet service']
------------------------------
Contract
['Month-to-month' 'One year' 'Two year']
------------------------------
PaperlessBilling
['Yes' 'No']
------------------------------
PaymentMethod
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
------------------------------
Churn
['No' 'Yes']
------------------------------
TenureGroup
['0-12' '25-48' '13-24' '49-72']
------------------------------
MonthlyChargeCategory
['Low' 'Medium' 'High']
------------------------------

In [96]:
df.nunique()

gender                      2
SeniorCitizen               2
Partner                     2
Dependents                  2
tenure                     72
PhoneService                2
MultipleLines               3
InternetService             3
OnlineSecurity              3
OnlineBackup                3
DeviceProtection            3
TechSupport                 3
StreamingTV                 3
StreamingMovies             3
Contract                    3
PaperlessBilling            2
PaymentMethod               4
MonthlyCharges           1584
TotalCharges             6530
Churn                       2
TotalServices              10
TenureGroup                 4
MonthlyChargeCategory       3
LongTermCustomer            2
dtype: int64

### Observation

The dataset contains both binary and multi-category categorical features. Binary features will be encoded using label mapping, while multi-category features will be transformed using one-hot encoding.

In [97]:
# Encode Target Variable

df['Churn'] = df['Churn'].map({
    "Yes":1,
    "No":0,
})
df["Churn"].value_counts()

Churn
0    5163
1    1869
Name: count, dtype: int64

### Observation

The target variable (`Churn`) was converted from categorical values ("Yes" and "No") to binary values (1 and 0). This format is required because machine learning models operate on numerical target labels.

<!-- ### Observation

The target varibale was converted from text labels ("Yes" and "No") into binary numerical values (1 and 0).  -->

In [98]:
## Encode Binary Values

binary_columns =[
    "gender",
    "Partner",
    "Dependents",
    "PhoneService",
    "PaperlessBilling"
]

for col in binary_columns:
    df[col] = df[col].map({
        'Yes':1,
        "No":0,
        "Male":1,
        "Female":0
    })

In [99]:
 df[binary_columns].head()

   gender  Partner  Dependents  PhoneService  PaperlessBilling
0       0        1           0             0                 1
1       1        0           0             1                 0
2       1        0           0             1                 1
3       1        0           0             0                 0
4       0        0           0             1                 1

### Observation

Binary categorical features such as `gender`, `Partner`, `Dependents`, `PhoneService`, and `PaperlessBilling` were encoded into numerical values. This transformation saves the original information while making these features suitable for machine learning algorithms.

<!-- ### Observation

Binary categorical variables were converted into numerical values while preserving their original meaning. -->

In [100]:
# One-Hot Encode multi-class features

multi_columns =["MultipleLines",
                "InternetService",
                "OnlineSecurity",
                "OnlineBackup",
                "DeviceProtection",
                "TechSupport",
                "StreamingTV",
                "StreamingMovies",
                "Contract",
                "PaymentMethod",
                "TenureGroup",
                "MonthlyChargeCategory"]
df= pd.get_dummies(
    df,
    columns=multi_columns,
    dtype=int
)

df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,...,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,TenureGroup_0-12,TenureGroup_13-24,TenureGroup_25-48,TenureGroup_49-72,MonthlyChargeCategory_High,MonthlyChargeCategory_Low,MonthlyChargeCategory_Medium
0,0,0,1,0,1,0,1,29.85,29.85,0,...,0,1,0,1,0,0,0,0,1,0
1,1,0,0,0,34,1,0,56.95,1889.50,0,...,0,0,1,0,0,1,0,0,0,1
2,1,0,0,0,2,1,1,53.85,108.15,1,...,0,0,1,1,0,0,0,0,0,1
3,1,0,0,0,45,0,0,42.30,1840.75,0,...,0,0,0,0,0,1,0,0,0,1
4,0,0,0,0,2,1,1,70.70,151.65,1,...,0,1,0,1,0,0,0,1,0,0

<!-- ### Observation

Multi-category variables were transformed into dummy variables using one-hot encoding. The first category was dropped to reduce redundancy and avoid multicollinearity. -->

In [101]:
# Verify Encoded Dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 50 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   gender                                   7032 non-null   int64
 1   SeniorCitizen                            7032 non-null   int64
 2   Partner                                  7032 non-null   int64
 3   Dependents                               7032 non-null   int64
 4   tenure                                   7032 non-null   int64
 5   PhoneService                             7032 non-null   int64
 6   PaperlessBilling                         7032 non-null   int64
 7   MonthlyCharges                           7032 non-null   float64
 8   TotalCharges                             7032 non-null   float64
 9   Churn                                    7032 non-null   int64
 10  TotalServices                            7032 non-null   int64
 11  LongTermCustomer                         7032 non-null   int64
 12  MultipleLines_No                         7032 non-null   int32
 13  MultipleLines_No phone service           7032 non-null   int32
 14  MultipleLines_Yes                        7032 non-null   int32
 15  InternetService_DSL                      7032 non-null   int32
 16  InternetService_Fiber optic              7032 non-null   int32
 17  InternetService_No                       7032 non-null   int32
 18  OnlineSecurity_No                        7032 non-null   int32
 19  OnlineSecurity_No internet service       7032 non-null   int32
 20  OnlineSecurity_Yes                       7032 non-null   int32
 21  OnlineBackup_No                          7032 non-null   int32
 22  OnlineBackup_No internet service         7032 non-null   int32
 23  OnlineBackup_Yes                         7032 non-null   int32
 24  DeviceProtection_No                      7032 non-null   int32
 25  DeviceProtection_No internet service     7032 non-null   int32
 26  DeviceProtection_Yes                     7032 non-null   int32
 27  TechSupport_No                           7032 non-null   int32
 28  TechSupport_No internet service          7032 non-null   int32
 29  TechSupport_Yes                          7032 non-null   int32
 30  StreamingTV_No                           7032 non-null   int32
 31  StreamingTV_No internet service          7032 non-null   int32
 32  StreamingTV_Yes                          7032 non-null   int32
 33  StreamingMovies_No                       7032 non-null   int32
 34  StreamingMovies_No internet service      7032 non-null   int32
 35  StreamingMovies_Yes                      7032 non-null   int32
 36  Contract_Month-to-month                  7032 non-null   int32
 37  Contract_One year                        7032 non-null   int32
 38  Contract_Two year                        7032 non-null   int32
 39  PaymentMethod_Bank transfer (automatic)  7032 non-null   int32
 40  PaymentMethod_Credit card (automatic)    7032 non-null   int32
 41  PaymentMethod_Electronic check           7032 non-null   int32
 42  PaymentMethod_Mailed check               7032 non-null   int32
 43  TenureGroup_0-12                         7032 non-null   int32
 44  TenureGroup_13-24                        7032 non-null   int32
 45  TenureGroup_25-48                        7032 non-null   int32
 46  TenureGroup_49-72                        7032 non-null   int32
 47  MonthlyChargeCategory_High               7032 non-null   int32
 48  MonthlyChargeCategory_Low                7032 non-null   int32
 49  MonthlyChargeCategory_Medium             7032 non-null   int32
dtypes: float64(2), int32(38), int64(10)
memory usage: 1.7 MB

In [102]:
df.shape

(7032, 50)

### Observation

Multi-category categorical features were transformed into dummy variables using one-hot encoding. The `drop_first=True` parameter was used to remove one category from each feature, reducing redundancy and helping prevent multicollinearity. The dataset is now fully numerical and ready for machine learning.

<!-- ### Observation

All categorical features have been successfully converted into numerical representation. This dataset is now suitable for machine learning algorithms. -->

In [103]:
# # Save encoded dataset

# df.to_csv("../data/processed/encoded_telco_churn.csv", index=False)

<!-- # Summary

### Key Findings 

The encoding process successfully converted categorical variables into numerical features suitable for machine learning models.

The following tasks were completed:

- Encoded the target variable.
- Converted binary categorical features into numerical values
- Applied one-hot encoding to multi-category features.
- Saved the encoded dataset for model training.

The encoded dataset is now ready for machine learning model developement. -->